### ISSUE TITLE
Kek Pernah Liat

### ISSUE THREAD

**Issue by tahaluindo** [ryuzein/Pandawa-Eazy-Tools#6]
Udah Jelas² Ini Punyaku Di Sofware-Tools [LINK](https://github.com/ryuzein/Pandawa-Eazy-Tools/tree/main/IPTV) lawak apa gimana deck?

**Comment by ryuzein** [comment]
Iyh kan saya sudah bilang kalo ngambil dari beberapa referensi juga. Lagian punyamu kan emang open source?. Seharusnya kan bebas dikembangkan
